language: android
jdk:
 - oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    
before_script:
    - chmod +x gradlew
    - echo yes | android update sdk --no-ui --all --filter platform-tools,tools --force > /dev/null
    - echo yes | android update sdk --no-ui --all --filter build-tools-24.0.0 --force > /dev/null
    - echo yes | android update sdk --no-ui --all --filter android-24 --force > /dev/null
    - echo yes | android update sdk --no-ui --all --filter extra-android-support --force > /dev/null
    - echo yes | android update sdk --no-ui --all --filter extra-android-m2repository --force > /dev/null

script:
  ./gradlew :app:clean :app:check

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.12