language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0 rc3
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    
before_script:
    - chmod +x gradlew

script: ./gradlew clean check -s -d
